# Generated by Django 2.2.1 on 2019-05-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdt', '0002_auto_20150604_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpdt',
            name='flag',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='paypalpdt',
            name='test_ipn',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
